version: "3"
services:
  web:
    image: daocloud.io/library/nginx:latest
    privileged: true
    # build:
    #    context: .
    volumes:
      - ./dist:/usr/share/nginx/html
    ports: 
      - 8000:80
