version: "3.4"
# change the network name {net_name} to the app network

services:
  web:
    image: nginx:stable
    privileged: true
    restart: always
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
      - ./mysql-expose.mod:/etc/nginx/conf.d/mysql-expose.mod
      - ./dist:/usr/share/nginx/html
    ports:
      - 8000:80
    network_mode: net_name 
