version: "3.4"
services:
  api:
    # image: adoptopenjdk:11-jre-hotspot
    image: zelejs/allin-web:jdk11
    working_dir: /webapps
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./:/webapps
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    environment: 
      TZ: Asia/Shanghai
    #    JAVA_OPTS: "$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    command:
      - /bin/sh
      - -c
      - |
        java -jar *.jar --server.port=8080
#       java $JAVA_OPTS -jar *.jar --spring.profiles.active=test --server.port=8080        
#       java "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n" -jar *.jar --server.port=8080        
