version: "3.4"
# change the network name {net_name} to the app network

services:
  web:
    image: nginx:stable
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1k"  
    volumes: 
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - 8000:80
    network_mode: net_name 
