version: "3.4"
# change the network name {net_name} to the app network

services:
  web:
    image: nginx:stable
    privileged: true
    restart: always
    volumes: 
      - ./dist:/usr/share/nginx/html
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    network_mode: net_name 
